version: "3"
services:
  client:
    image: node:12.18.3
    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./client
        target: /code
    working_dir: /code
    command: bash -c "npm install && npm run dev && npm start"
  server:
    image: node:12.18.4
    working_dir: /code
    ports:
      - 4000:4000
    environment:
      - DB_NAME=shelter
      - DB_CONNECTION=mongodb://futureproof:shelterpass@db:27017
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./server
        target: /code
    command: bash -c "npm install && npm run dev"

  db:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - "dbdata:/var/lib/mongodb/data"
      - "./db/seeds.js:/docker-entrypoint-initdb.d/seeds.js:ro"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=futureproof
      - MONGO_INITDB_DATABASE=shelter
      - MONGO_INITDB_ROOT_PASSWORD=shelterpass
volumes:
  dbdata:
